apiVersion: apps/v1
kind: ReplicaSet
metadata:
    name: rc03
    labels:
      tier: one
      app: webserver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webserver
  template:
      metadata:
          name: web-container
          labels:
            app: webserver
      spec:
        containers:
          - name: web-container
            image: nginx
            ports:
              - containerPort: 80
                hostPort: 8888

