apiVersion: v1
kind: ReplicationController
metadata:
  name: webserver-rc
  labels:
    env: development
spec:
  replicas: 3
  template:
    metadata:
      name: webserver-pod
      labels:
        env: development01
    spec:
      containers:
        - name: httpd-demo
          image: httpd
          ports:
            - containerPort: 80
              hostPort: 8080
